#!/bin/bash
set -ex 

base_dir=$HOME/AmpliconPE/
bin_dir=$base_dir/bin/
data_dir=$base_dir/data/
TuBa_FASTQs=$data_dir/TuBa-seq_FASTQs/
TuBa_master_read='GGGACCCGGANNNNNNNNAANNNNNTTNNNNNAANNNNNATGCCCAAGA'

ls -d $TuBa_FASTQs/* | parallel "$bin_dir/derep.py {} $TuBa_master_read"

$bin_dir/consolidate.py $TuBa_FASTQs;


