#!/bin/bash

tuba_dir=~/tuba-seq

MY_barcodes="AAACAAGTTGGGATAAGCCAC AAATTCCTTGGCGCAATTACA AAGCTAATTGACGAAAGGCCT AATCTTTTTCCATCAAATTGC AACGCCGTTCTAGGAATTTCA AAGTCGATTTGGTAAACACCC AAGTTTGTTTCGGGAATGCAG"

set -ex 

$tuba_dir/bin/tumor_calls.py --sgRNA_file data/sgRNA_info.csv -p --min_cells=10 --spike_barcodes $MY_barcodes --report; 


