#!/bin/bash
set -ex 

AmpliconPE_dir=$HOME/AmpliconPE

$AmpliconPE_dir/bin/TuBa-seq.py --sgRNA_file $AmpliconPE_dir/data/sgRNA_info.csv --parallel True --FASTQ_directory $AmpliconPE_dir/data/TuBa-seq_FASTQs; 


